/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// import { useFrame, useThree } from '@react-three/fiber'
import {a} from '@react-spring/three'

import pianoScene from '../assets/3d/modified_piano.glb'

const Piano = (props: any) => {
  const pianoRef = useRef();
    
  const { nodes, materials } = useGLTF(pianoScene) as any
  return (
      <a.group ref={pianoRef} {...props}>
          <mesh
        geometry={nodes.polySurface3805_phongE13_0_1.geometry}
        material={materials.phongE13}
      />
      <mesh     
        geometry={nodes.polySurface3805_phongE13_0_2.geometry}
        material={materials.phongE15}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_3.geometry}
        material={materials.phongE5}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_4.geometry}
        material={materials.phongE6}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_5.geometry}
        material={materials.phongE7}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_6.geometry}
        material={materials.phongE8}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_7.geometry}
        material={materials.phong2}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_8.geometry}
        material={materials.phongE3}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_9.geometry}
        material={materials.phongE14}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_10.geometry}
        material={materials.lambert55}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_11.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_12.geometry}
        material={materials.lambert27}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_13.geometry}
        material={materials.phongE9}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_14.geometry}
        material={materials.phongE4}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_15.geometry}
        material={materials.lambert56}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_16.geometry}
        material={materials.lambert28}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_17.geometry}
        material={materials.phongE11}
      />
    </a.group>
  )
}


export default Piano