/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { a, useSpring } from '@react-spring/three'
import { useDrag } from '@use-gesture/react'

import pianoScene from '../assets/3d/modified_piano.glb'

const Piano = (props: any) => {
  const pianoRef = useRef<any>();
  const { nodes, materials } = useGLTF(pianoScene) as any
  const [isDragging, setIsDragging] = useState(false);

  // Add rotation spring
  const [spring, api] = useSpring(() => ({
    rotation: [0, 0, 0],
    config: { mass: 1, tension: 170, friction: 26 }
  }));

  // Auto-rotation when not dragging
  useFrame((_state, delta) => {
    if (pianoRef.current && !isDragging) {
      pianoRef.current.rotation.y += delta * 0.3;
    }
  });

  // Drag handler
  const bind = useDrag(({ offset: [x, y], active }) => {
    setIsDragging(active);
    if (pianoRef.current) {
      api.start({
        rotation: [y / 100, x / 100, 0]
      });
    }
  }, { filterTaps: true });

  return (
    <a.group
      ref={pianoRef}
      {...props}
      {...bind()}
      {...spring}
    >
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_1.geometry}
        material={materials.phongE13}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_2.geometry}
        material={materials.phongE15}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_3.geometry}
        material={materials.phongE5}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_4.geometry}
        material={materials.phongE6}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_5.geometry}
        material={materials.phongE7}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_6.geometry}
        material={materials.phongE8}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_7.geometry}
        material={materials.phong2}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_8.geometry}
        material={materials.phongE3}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_9.geometry}
        material={materials.phongE14}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_10.geometry}
        material={materials.lambert55}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_11.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_12.geometry}
        material={materials.lambert27}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_13.geometry}
        material={materials.phongE9}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_14.geometry}
        material={materials.phongE4}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_15.geometry}
        material={materials.lambert56}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_16.geometry}
        material={materials.lambert28}
      />
      <mesh
        geometry={nodes.polySurface3805_phongE13_0_17.geometry}
        material={materials.phongE11}
      />
    </a.group>
  )
}

export default Piano